### ISSUE TITLE
Not reporting on contracts using the delegateProxy pattern

### ISSUE THREAD

**Issue by elenadimitrova** [cgewecke/eth-gas-reporter#106]
Contracts calls using a delegate proxy (for upgradability) aren't reported on. This used to work in v0.1.2 but no longer does. @area suspects [this change](https://github.com/cgewecke/eth-gas-reporter/commit/90ea9deb6cfef8b4b241ee3c02871a541e896e68) might have introduced it. 

For sample outputs see working examples in our Circle builds under "" 
Broken (using v0.1.12): https://circleci.com/gh/JoinColony/colonyNetwork/5654#artifacts/containers/0
Working (using v0.1.2): https://circleci.com/gh/JoinColony/colonyNetwork/4841

**Comment by cgewecke** [comment]
Hi @elenadimitrova :) 

Have made headway on this with `0.2.0` although there are still issues. I've added colonyNetwork's gas tests to a job in CI here so you can see the differences between your current output and the new version:

+ [colonyNetwork at origin](https://circleci.com/gh/JoinColony/colonyNetwork/7889)
+ [colonyNetwork at eth-gas-reporter](https://travis-ci.org/cgewecke/eth-gas-reporter/jobs/529430555#L1432) 

The main problem is that some contracts have method signatures which shadow each other. If they're called through the router the reporter has to guess the target and just picks the first match. For example, in your current report you have results for `NoLimitSubdomains` that `0.2.0` attributes to `Colony`. Numbers look about the same. Neither contract is reported in the deployments table. 

Really fixing this and making it accurate/reliable will require more thought. 

Related issues: #94, #64

**Comment by elenadimitrova** [comment]
Thanks @cgewecke this is already a lot better as all of the deployed contracts are reported. 
Also on the function signature overlap it has improved as `NoLimitSubdomains` which was wrongly reported before e.g. [here](https://circleci.com/gh/JoinColony/colonyNetwork/7923) now correctly report the right `Colony` contract [here](https://circleci.com/gh/JoinColony/colonyNetwork/7942). Maybe it's because it first sees these functions defined there as you say but still.
I'm going to merge this upgrade so we're back to tracking latest versions. Thanks for the support.

**Comment by cgewecke** [comment]
Thanks @elenadimitrova!

**Comment by cgewecke** [comment]
@elenadimitrova 

`0.2.2` includes support for proxy resolvers (#126) and ships with an EtherRouter handler. However, it turns out you don't benefit from this because in your case the 'wild guess' strategy generates the same data, more quickly, (LOL). However, if you notice missing data in the future you can add the following to your reporterOptions and it should help:
```js
proxyResolver: 'EtherRouter',
```

There *is* a new thing in `0.2.2` you might find useful since you're on Circle. You can now get something like "coveralls for gas" in CI thanks to a (free) service called codechecks that MakerDAO engineer Chris Kaczor has been building. It looks like this and includes a diff report for gas changes relative to the PRs target branch:

![Screen Shot 2019-06-18 at 12 25 49 PM](https://user-images.githubusercontent.com/7332026/59713894-47298900-91c5-11e9-8083-233572787cfa.png)

If you have any interest in trying it out I can open a PR configuring it at colonyNetwork.  If not - no problem :)  There are also setup instructions and more info [here](https://github.com/cgewecke/eth-gas-reporter/blob/master/docs/codechecks.md).

**Comment by cgewecke** [comment]
Closing - [colonyNetwork 669](https://github.com/JoinColony/colonyNetwork/issues/669)
