### ISSUE TITLE
npm install fails in CI due to web3

### ISSUE THREAD

**Issue by abcoathup** [cgewecke/eth-gas-reporter#153]
Adding eth-gas-reporter results in npm install failing in CI

```
$ npm install
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/eth-gas-reporter/node_modules/web3-providers-ws/websocket@git:/github.com/frozeman/WebSocket-Node.git#6c72925e3f8aaaea8dc8450f97627e85263999f2" as it does not contain a package.json file.
```

**Comment by cgewecke** [comment]
@abcoathup Thanks for reporting. 

Not sure what's going on here - I wasn't able to reproduce locally. It  seems similar to #139 which had a short-term workaround of using `yarn` instead of `npm install`.

[This](https://github.com/frozeman/WebSocket-Node/tree/6c72925e3f8aaaea8dc8450f97627e85263999f2) is the repo state at the commit referenced in the error and it *does* [contain a package.json](https://github.com/frozeman/WebSocket-Node/blob/6c72925e3f8aaaea8dc8450f97627e85263999f2/package.json).  

Do you have a package-lock.json in the repo that consumes the reporter?

**Comment by justinjmoses** [comment]
I get the same thing [on CircleCI](https://circleci.com/gh/Synthetixio/synthetix/219), though [not on Travis](https://travis-ci.org/Synthetixio/synthetix/builds/559477861) interestingly.

**Comment by cgewecke** [comment]
@justinjmoses Hmmmm. Very interesting. 

It looks like the travis run has a different post-run crash from this package which also needs investigation....
``` 
 1) "after each" hook
[1] /home/travis/build/Synthetixio/synthetix/node_modules/eth-gas-reporter/lib/gasTable.js:260
[1]       ? fs.writeFileSync(outputFile, tableOutput)
[1]                          ^
[1] 
[1] ReferenceError: outputFile is not defined
```

**Comment by cgewecke** [comment]
@abcoathup @justinjmoses I'm going publish a patch shortly that gets rid of the npm shrinkwrap.json (which is probably the source of installation probs) and fixes the `outputFile` bug (which is  a misnamed variable).

**Comment by cgewecke** [comment]
@abcoathup @justinjmoses `0.2.6`?

@justinjmoses I notice you're writing the table to file - we've recently added an (experimental) feature that displays the table in the github UI and calculates the gas usage diff between a pull request and its target branch, coveralls style. If you have any use for that there's more info [here](https://github.com/cgewecke/eth-gas-reporter/blob/master/docs/codechecks.md).

**Comment by justinjmoses** [comment]
Hey @cgewecke - yeah wow, I was going to file another issue but had to run to a meeting. 💯for that investigation! 

I'm outputting it to a file because [we're using concurrently to start ganache and run the tests](https://github.com/Synthetixio/synthetix/blob/master/package.json#L14-L15), without using the file solution, concurrently would kill the process after the tests ran but before the gas reporter had a chance to finish its output. 

Yes I just saw that codechecks addition today - I'm going to look into adding it soon. 👍👍👍

**Comment by justinjmoses** [comment]
Hmmm. I'm getting an issue with `solidity-parser-antlr` - seems like `0.4.6` doesn't like parsing emitted functions. truffle fails immediately due to the gas reporter building up the AST:

https://github.com/federicobond/solidity-parser-antlr/blob/master/src/ASTBuilder.js#L327 dies while [parsing this Solidity code](https://github.com/Synthetixio/synthetix/blob/master/contracts/ExternStateToken.sol#L188)

In the meantime, I explicitly add `0.4.2` as a dependency in my project (preventing your caret binding of `^0.4.2` versioning from taking `0.4.6`)

**Comment by cgewecke** [comment]
@justinjmoses Ah thanks so much. I'll pin that on my end.

**Comment by cgewecke** [comment]
Sidelight on this - I just installed something else that includes web3 using yarn and it emits a (possibly) relevant warning and skips installation of the websocket module:
```
Pattern ["websocket@git://github.com/frozeman/WebSocket-Node.git#browserifyCompatible"] is trying to unpack in the same destination "/Users/cgewecke/Library/Caches/Yarn/v4/npm-websocket-1.0.26-6c72925e3f8aaaea8dc8450f97627e85263999f2/node_modules/websocket" as pattern ["websocket@1.0.26"]. This could result in non-deterministic behavior, skipping.
```

**Comment by justinjmoses** [comment]
@cgewecke https://github.com/Synthetixio/synthetix/pull/181/checks?check_run_id=170233757 :)

**Comment by cgewecke** [comment]
@justinjmoses Sweet! So cool. Thanks for trying it out.

**Comment by abcoathup** [comment]
@cgewecke rebuilding my `package-lock.json` didn't resolve the issue but updating to the new version of `eth-gas-reporter` did.  

Travis-ci now building: https://travis-ci.org/abcoathup/rockstar/builds/560256227 
So is a clean local `npm install` from a clone: https://github.com/abcoathup/rockstar

Thanks.  I created the repo for the tutorial: https://forum.zeppelin.solutions/search?q=rockstar

Looks like this can be closed.
