### ISSUE TITLE
Ability to display two different checks

### ISSUE THREAD

**Issue by ajsantander** [cgewecke/eth-gas-reporter#217]
We're using gas reports currently in Synthetix, e.g. https://github.com/Synthetixio/synthetix/pull/728/checks?check_run_id=1125774785

As you can see in that PR, we're working with forks. Basically, what we're trying to do is to run a bunch of production tests on top of a fork of mainnet.

I would like to be able to have two different gas reports, one for unit tests (as shown in the link above), and a different one for production tests. Right now, we're outputting 2 files, `test-gas-used.log`, and `test-gas-used-prod.log`, but we're not sure how to get this to an actual report.

Also, while I'm here, is there a way to cause the CI to fail given a diff in gas usage above a certain threshold?

**Comment by cgewecke** [comment]
Hi @ajsantander. Thanks for opening. Some initial thoughts... 

> I would like to be able to have two different gas reports, one for unit tests (as shown in the link above), and a different one for production tests. Right now, we're outputting 2 files, test-gas-used.log, and test-gas-used-prod.log, but we're not sure how to get this to an actual report.

Will look into this...it's possible Codechecks already supports it.

In the most recent Synthetix runs it seems like the diff is still not being reported.  

Recent PRs here using Travis [show the expected output][1], so it doesn't seem to be a problem with the Codechecks service as a whole or anything. However, will need to figure out how to get it working correctly with CircleCI...

> Also, while I'm here, is there a way to cause the CI to fail given a diff in gas usage above a certain threshold?

That's a good idea. Would have to add some logic here but this should be simple to implement. Will open as a separate issue.

 [1]: https://github.com/cgewecke/eth-gas-reporter/pull/216/checks?check_run_id=1105256793

**Comment by ajsantander** [comment]
@cgewecke any progress with this? Pls let us know how we can help.

**Comment by cgewecke** [comment]
@ajsantander Apologies, I should be able to look into this and other issues at buidler-gas-reporter in the next couple days...

Thanks for pinging.

**Comment by cgewecke** [comment]
There's support for this now in eth-gas-reporter 0.2.18 / buidler-gas-reporter 0.1.4. 

(At synthetix you'll need to upgrade buidler-gas-reporter since you're using a beta)

+ guide to generating [multiple reports per PR][1]
+ working example: https://github.com/cgewecke/gas-check/pull/36 
+ docs about new [failure threshold options][2] 

[1]: https://github.com/cgewecke/eth-gas-reporter/blob/master/docs/codechecks.md#multiple-reports-for-different-ci-jobs
[2]: https://github.com/cgewecke/eth-gas-reporter/blob/master/docs/codechecks.md#failure-thresholds

An example with two reports, one failing a threshold setting looks like:

![Screen Shot 2020-10-13 at 6 10 43 PM](https://user-images.githubusercontent.com/7332026/95932023-8ea33380-0d7f-11eb-898c-1fa7bc7d234d.png)


@ajsantander 

If you have a chance, could you double-check that the Codechecks api token, `CC_SECRET` was transferred to CircleCI? When you go to https://app.codechecks.io/, you should see something like this where the token is available for copying...
 
![Screen Shot 2020-10-13 at 5 55 15 PM](https://user-images.githubusercontent.com/7332026/95931242-6dd9de80-0d7d-11eb-95b5-c07e585080fa.png)

Please just lmk about any problems you run into, will leave this open for now...

**Comment by cgewecke** [comment]
Another note: [ganache-core 625][1] reports that there's a difference between forked and non-forked gas costs for SSTORE which looks like a bug.

[1]: https://github.com/trufflesuite/ganache-core/issues/625

**Comment by justinjmoses** [comment]
Thanks Chris :pray: 

Yep, the secret is in CircleCI.

**Comment by ajsantander** [comment]
Thanks @cgewecke 
We'll be implementing this ASAP 🙏

**Comment by ajsantander** [comment]
@cgewecke FYI,

This is where we're implementing this https://github.com/Synthetixio/synthetix/pull/805
So far, it appears to work seamlessly. We'll let you know if we encounter any problems in the future.

**Comment by cgewecke** [comment]
@ajsantander Ok awesome! Will close here and keep an eye out over there. Thanks!
