### ISSUE TITLE
Support Web3 1.0

### ISSUE THREAD

**Issue by cgewecke** [cgewecke/eth-gas-reporter#62]
The gas reporter inherits web3 from the Truffle test environment and it's likely this will be upgraded to Web3 1.0 soon. Sync web3 methods will be async.

(Suggested via email by Sai)

**Comment by area** [comment]
> Sync web3 methods will be async.

Such a simple change. Such a pain...

So for reasons that don't need exploring at this juncture, I have had reason to fix this. The `EventEmitter` used by mocha does not support async functions (or rather, does not support waiting for them to complete). There is some discussion about this [here](https://github.com/mochajs/mocha/issues/2541#issuecomment-254144057), but I really did not want to have to make a PR to `mocha` to fix this. Just using `async` anyway caused `truffle` to revert the `ganache` state while the hooks were trying to read the relevant transaction data, and so little to no stats were collected. I tried to use `deasync`, but could not get past segfault issues on OSX which seem to be [pretty common](https://github.com/abbr/deasync/issues/55). I considered using `spawn-sync`, but have ended up just repimplementing the RPC calls required in a sync fashion by using `request-sync`; the `web3` passed by truffle is only used to work out what the address of the RPC endpoint is.

My solution can be found on [my fork](https://github.com/area/eth-gas-reporter/tree/manual-sync-requests); I'm not making this a PR because there are probably better ways of achieving this that I've not considered (perhaps by diving deeper in to`mocha`), but if you wanted to go down this road, which seems the easiest, at least, it's there.

**Comment by area** [comment]
It'd be a pretty straightforward PR to review. I've gone a bit belt-and-braces on conversions between hex strings and numbers, and one function is defined in both `index.js` and `gasStats`, so there's a little room to improve - I'd try and sort both of those out more nicely if it was going to end up in this package.

**Comment by cgewecke** [comment]
@area Ok well belt-and-braces is also fine if you're busy, we can always do a little refactoring another day :)
