### ISSUE TITLE
Disable while running coverage

### ISSUE THREAD

**Issue by asoong** [cgewecke/eth-gas-reporter#96]
Hey there, just came across this tool, but have been using the solidity-coverage tool for a while now. I noticed both profilers increase the workflow time on ci by quite a bit [before](https://circleci.com/gh/SetProtocol/set-protocol-contracts/1144) vs. [after](https://circleci.com/gh/SetProtocol/set-protocol-contracts/1142). In my workflow, I parallelized running tests only and coverage. Wondering if there's a way to only have gas reporting on the tests.

**Comment by cgewecke** [comment]
@asoong Yes. Conventionally there's a container that just runs `truffle test` and another one that runs coverage. We actually recommend that coverage not be used as an equivalent to `truffle test` because it injects a lot of Solidity code into the contracts and it's nice to have a coverage-free baseline to make sure that nothing's getting distorted. 

The main author of solidity-coverage works at JoinColony and they also run both of these tools. Their CI config is [here](https://github.com/JoinColony/colonyNetwork/blob/develop/.circleci/config.yml). Probably also check out their `package.json` and `truffle.js`. 

A travis example of separate containers for vanilla tests, gas tests, coverage, and a geth client can be seen at EthPM's [travis.yml](https://github.com/ethpm/escape-truffle/blob/master/.travis.yml) and at its [truffle.js](https://github.com/ethpm/escape-truffle/blob/master/truffle-config.js).
